### PR TITLE
use orchestrator.log name for log in task for source container

### PR DESCRIPTION
**Pull request by rcerven**
* OSBS-8378

Signed-off-by: Robert Cerven <rcerven@redhat.com>

Maintainers will complete the following section:
- [x] Commit messages are descriptive enough
- [x] "Signed-off-by:" line is present in each commit
- [ ] Code coverage from testing does not decrease and new code is covered
- [x] JSON/YAML configuration changes are updated in the relevant schema
- [ ] Pull request includes link to an osbs-docs PR for user documentation updates

### CODE REVIEW

**Comment by MartinBasti** [comment]
How regular builds determine name `orchestrator.log`?

**Comment by twaugh** [comment]
The usual path is through _write_demultiplexed_logs, where the log file to use is decide on based on fields in the log lines.

**Comment by athos-ribeiro** [comment]
It would be nicer to have this responsibility in the BuildSourceContainerTask class instead of adding an attribute for that, if feasible. Not sure how the best way to approach this would look like though. Maybe the log filename could be passed in a class attr or _write_combied_log could be refactored

**Comment by rcerven** [comment]
changed

**Comment by rcerven** [comment]
rn updated: use orchestrator.log name for log in task for source container

**Pull request merged**
