### PR TITLE
Install koji-c and deps for pylint run

### PR DESCRIPTION
**Pull request by athos-ribeiro**
Signed-off-by: Athos Ribeiro <athos@redhat.com>

# Maintainers will complete the following section

- [x] Commit messages are descriptive enough
- [x] "Signed-off-by:" line is present in each commit
- [x] Code coverage from testing does not decrease and new code is covered
- [x] JSON/YAML configuration changes are updated in the relevant schema
- [x] Pull request has a link to an osbs-docs PR for user documentation updates

### CODE REVIEW

**Comment by MartinBasti** [comment]
Hmm, why is pylint unhappy?

**Comment by athos-ribeiro** [comment]
@MartinBasti It checks for the imports. I Just included the whole koji-c setup. The first forced push included the revert commit. I cleaned it in the second push.

**Comment by SalatskySal** [comment]
> @MartinBasti It checks for the imports. I Just included the whole koji-c setup. The first forced push included the revert commit. I cleaned it in the second push.

@athos-ribeiro Thank you for this :+1:

**Comment by athos-ribeiro** [comment]
No release notes added. Test suite related change

**Pull request merged**
