### PR TITLE
change default channel for buildSourceContainer to container-source

### PR DESCRIPTION
**Pull request by rcerven**
Signed-off-by: Robert Cerven <rcerven@redhat.com>

# Maintainers will complete the following section

- [x] Commit messages are descriptive enough
- [x] Code coverage from testing does not decrease and new code is covered
- [n/a] JSON/YAML configuration changes are updated in the relevant schema
- [n/a] Pull request has a link to an osbs-docs PR for user documentation updates

### CODE REVIEW

**Review by ben-alkov — APPROVED** [review]

**Comment by chmeliik** [comment]
Could somebody remind me why we need it?

**Comment by rcerven** [comment]
> Could somebody remind me why we need it?
> 
> Is it just to make sure we have the correct default, or does this fix some problems for integration tests or something?

if we have default channel container, we need koji rule, but when there is koji rule, we can't use koji channel override

**Review by chmeliik — COMMENTED** [review]
Noticed that the docstring still says the default is "container"

Other than that LGTM

**Comment by rcerven** [comment]
> Noticed that the docstring still says the default is "container"
> 
> Other than that LGTM

removed that 'default channel' from the comment as it duplicates explicit param ...

**Review by chmeliik — APPROVED** [review]
LGTM :+1:

**Pull request merged**
