### PR TITLE
Put jsonschema definition directly in python file

### PR DESCRIPTION
**Pull request by chmeliik**
The package is installed in a specific way, which means the json file
will not be found in the expected location. To simplify things, let's
take advantage of the fact that jsonschema validation works with python
dictionaries and put the definition directly in builder_containerbuild.py.

Signed-off-by: Adam Cmiel <acmiel@redhat.com>

### CODE REVIEW

**Comment by athos-ribeiro** [comment]
Can you also include an OSBS comment in the commit?

**Comment by chmeliik** [comment]
Removed `package_data` and included OSBS issue number, thanks @athos-ribeiro

**Comment by chmeliik** [comment]
I believe the coverage decrease is due to a reduction in number of relevant lines (the entire `PARAMS_SCHEMA` definition counts as only one relevant line and some lines such as imports and opening files were removed)

**Comment by athos-ribeiro** [comment]
No release notes added. There is already an entry for this feature

**Pull request merged**
